<?php
/**
 * Framework options for Czech (cs_CZ) localization.
 * @package VisitPress
 * @since VisitPress 1.0
*/   
$visitpress_options = array (

array( "name" => $visitpress_themename ." nastavení",
	"type" => "title"),

array( "type" => "open"),

// Start Tabs
array( "name" => "Start Tabs",
		"type" => "tabs-open",
		"icon" => "layout"),

	// Home
	array( "name" => "Vítejte",
			"id" => "tab_menu_0",
			"type" => "tab",
			"icon" => "layout",
			"class" => " selected first"),
	
	// General Settings
	array( "name" => "Hlavní nastavení",
			"id" => "tab_menu_1",
			"type" => "tab",
			"icon" => "layout",
			"class" => ""),
		
	// Colors
	array( "name" => "Barvy",
			"id" => "tab_menu_3",
			"type" => "tab",
			"icon" => "layout",
			"class" => ""),
      
	// Fonts
	array( "name" => "Písma",
			"id" => "tab_menu_4",
			"type" => "tab",
			"icon" => "layout",
			"class" => ""),
      
	// Social Networking Tab
	array( "name" => "Sociální sítě",
			"id" => "tab_menu_5",
			"type" => "tab",
			"icon" => "layout",
			"class" => ""),
	
	// Other settings Tab
	array( "name" => "Další nastavení",
			"type" => "tab",
			"id" => "tab_menu_6",
			"class" => ""),
      
  // Get Premium Tab
	array( "name" => "ZÍSKAT PRÉMIOVOU VERZI",
			"type" => "tab",
			"id" => "tab_menu_7",
			"class" => ""),
	

// General setting Tab
array( "name" => "Close Tabs",
		"type" => "tabs-close",
		"icon" => "layout"),


array( "name" => "Start Container",
		"type" => "container-open",
		"icon" => "layout"),

// Home Container 0
array( "name" => "tab_content_0",
		"type" => "tabcontent-open",
		"display" => "block",
		"icon" => "layout"),

	// Home
	array( "name" => "Vítá Vás VisitPress!",
		"type" => "heading",
		"icon" => "layout"),
	
	array("name" => "Na úvod bych Vám chtěl poděkovat, že jste si vybrali šablonu VisitPress! Pevně věřím, že budete s produktem spokojeni. V případě jakýchkoli problémů či nejasností můžete využít <a href='http://visitpress.tomastoman.cz/support' target='_blank'>Oficiální zákaznickou podporu</a> (v anglickém, německém nebo českém jazyce).",
		"type" => "infotext"),
	
		array( "name" => "O VisitPressu",
		"type" => "heading",
		"icon" => "layout"),
	
	array("name" => "Byli jste už v Toskánsku? Máte rádi Paříž? Navštívili jste už někdy Amsterdam? S VisitPressem můžete prozkoumat všechna tato místa. Chybí Vám zde Vaše oblíbené místo? Nevadí! Můžete jednoduše vytvářet Vaše vlastní barevné kombinace, které budou dokonale odpovídat Vašim oblíbeným lokalitám. Samozřejmě můžete VisitPress použít i pro jiné účely než cestování! :-)<br /><br />VisitPress je snadno přizpůsobitelná blogovací šablona pro redakční systém WordPress. Jedná se o plně responzivní šablonu, která umožňuje snadné prohlížení stránek na jakémkoli zařízení.",
		"type" => "infotext"),

array( "name" => "tab_content_0",
		"type" => "tabcontent-close",
		"icon" => "layout"),
// Close Home

// General setting Tab Container 1
array( "name" => "tab_content_1",
		"type" => "tabcontent-open",
		"display" => "none",
		"icon" => "layout"),

	// General settings
	array( "name" => "Hlavní nastavení",
		"type" => "heading",
		"icon" => "layout"),		

	array( "name" => "Barevná kombinace",
		"desc" => "Vyberte jednu z předpřipravených barevných kombinací. Pod záložkou Barvy můžete vytvářet vlastní barevné kombinace.",
		"id" => $visitpress_shortname."_css",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Tuscany (default)',
							'b' => 'Amsterdam',
              'c' => 'Paris',),
		"type" => "select"),
    
  array( "name" => "Zobrazovat postranní sloupec",
		"desc" => "Vyberte, zdali se má (Display) nebo nemá (Hide) zobrazovat pravý postranní sloupec.",
		"id" => $visitpress_shortname."_display_sidebar",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
    
	array( "name" => "URL adresa favikony",
		"desc" => "Nahrajte Vaši vlastní favikonu (16x16px) prostřednictvím nabídky <a href='media-new.php' target='_blank'>Nahrát soubor</a>. Vlastní favikonu můžete vytvořit s použitím <a title='Online Favicon Generator' href='http://www.favicon.cc/' target='_blank'>Favicon generatoru</a>.",
		"id" => $visitpress_shortname."_favicon_url",
		"type" => "text",
		"std" => ""),
    
  array( "name" => "Nadpis úvodní stránky",
	"desc" => "Vložte zde nadpis, který se objeví nad výpisem příspěvků na úvodní stránce. Pokud si nepřejete zobrazovat žádný nadpis, nechte toto pole prázdné.",
		"id" => $visitpress_shortname."_index_headline",
		"type" => "text",
		"std" => ""),
    
  array( "name" => "Zobrazovat drobečkovou navigaci",
		"desc" => "Vyberte, zdali se má (Display) nebo nemá (Hide) zobrazovat drobečková navigace. Plugin Breadcrumb NavXT musí být aktivní, pokud se drobečková navigace má zobrazovat.",
		"id" => $visitpress_shortname."_display_breadcrumb",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
	
	
	array( "name" => "Navigace mezi příspěvky",
		"desc" => "Tato nabídka dává možnost snadného procházení mezi jednotlivými příspěvky v chronologickém pořádí.",
		"id" => $visitpress_shortname."_next_preview_post",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
    	

	// HEADER
	array( "name" => "Nastavení záhlaví",
		"type" => "heading",
		"icon" => "layout"),
    
  array( "name" => "Šířka hlavního nadpisu",
		"desc" => "Nastavte šířku hlavního nadpisu a popisu webu (procentuelně vůči šířce stránky).",
		"id" => $visitpress_shortname."_page_title_width",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => '50%',
							'b' => '0%',
              'c' => '10%',
              'd' => '20%',
              'e' => '30%',
              'f' => '40%',
              'g' => '60%',
              'h' => '70%',
              'i' => '80%',
              'j' => '90%',
              'k' => '100%'),
		"type" => "select"),
    
  array( "name" => "Šířka navigace v záhlaví",
		"desc" => "Nastavte šířku navigace v záhlaví (procentuelně vůči šířce stránky).",
		"id" => $visitpress_shortname."_header_menu_width",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => '50%',
							'b' => '0%',
              'c' => '10%',
              'd' => '20%',
              'e' => '30%',
              'f' => '40%',
              'g' => '60%',
              'h' => '70%',
              'i' => '80%',
              'j' => '90%',
              'k' => '100%'),
		"type" => "select"),
    
    array( "name" => "Formát navigace v záhlaví",
		"desc" => "Nastavte, zdali se má navigace v záhlaví zobrazovat ve výchozím formátu (Default), nebo jako rozbalovací nabídka (Drop-down).",
		"id" => $visitpress_shortname."_header_menu_format",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Default',
              'b' => 'Drop-down'),
		"type" => "select"),
  
  
  // POSTS
	array( "name" => "Nastavení příspěvků",
		"type" => "heading",
		"icon" => "layout"),
    
  array( "name" => "Zobrazovat náhledové obrázky u jednotlivých příspěvků",
		"desc" => "Vyberte, zdali se mají (Display) nebo nemají (Hide) zobrazovat náhledové obrázky u jednotlivých příspěvků.",
		"id" => $visitpress_shortname."_display_image_post",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
    
  array( "name" => "Zobrazovat datum publikování",
		"desc" => "Vyberte, zdali se má (Display) nebo nemá (Hide) zobrazovat datum publikování u jednotlivých příspěvků.",
		"id" => $visitpress_shortname."_display_date_post",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
	
	array( "name" => "Zobrazovat autora",
		"desc" => "Vyberte, zdali se má (Display) nebo nemá (Hide) zobrazovat autor u jednotlivých příspěvků.",
		"id" => $visitpress_shortname."_display_author_post",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
    
  array( "name" => "Zobrazovat rubriky",
		"desc" => "Vyberte, zdali se mají (Display) nebo nemají (Hide) zobrazovat rubriky u jednotlivých příspěvků.",
		"id" => $visitpress_shortname."_display_categories_post",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),

// PAGES
	array( "name" => "Nastavení stránek",
		"type" => "heading",
		"icon" => "layout"),
    
  array( "name" => "Zobrazovat náhledové obrázky u stránek",
		"desc" => "Vyberte, zdali se mají (Display) nebo nemají (Hide) zobrazovat náhledové obrázky na jednotlivých stránkách.",
		"id" => $visitpress_shortname."_display_image_page",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select"),
    
  array( "name" => "Zobrazovat datum publikování",
		"desc" => "Vyberte, zdali se má (Display) nebo nemá (Hide) zobrazovat datum publikování na jednotlivých stránkách.",
		"id" => $visitpress_shortname."_display_date_page",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Hide',
							'b' => 'Display'),
		"type" => "select"),
		
	array( "name" => "Zobrazovat autora",
		"desc" => "Vyberte, zdali se má (Display) nebo nemá (Hide) zobrazovat autor na jednotlivých stránkách.",
		"id" => $visitpress_shortname."_display_author_page",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Hide',
							'b' => 'Display'),
		"type" => "select"),

//////////////////////////////////////

array( "name" => "tab_content_1",
		"type" => "tabcontent-close",
		"icon" => "layout"),
// Close General settings


// Colors Tab Container
array( "name" => "tab_content_3",
		"type" => "tabcontent-open",
		"display" => "none",
		"icon" => "layout"),

	// Text colors    
  array( "name" => "Barvy textů",
		"type" => "heading",
		"icon" => "layout"),
    
  array( "name" => "Barva obsahu stránek",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_body_color",
		"type" => "color",
		"std" => "#"),
  
  array( "name" => "Barva nadpisu webu",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_site_title_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva popisu webu",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_site_description_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva nadpisů stránek/příspěvků",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_headlines_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva nadpisů ve výpisu příspěvků",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_post_entry_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva data (den a měsíc) ve výpisu příspěvků",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_post_entry_date_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva data (rok) ve výpisu příspěvků",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_post_entry_year_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva nadpisů widgetů v postranním sloupci",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_sidebar_widget_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva nadpisů widgetů v zápatí",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_footer_widget_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva textů v zápatí",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_footer_text_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva odkazů v hlavní obsahové části",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_content_links_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva odkazů v postranním sloupci",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_sidebar_links_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva odkazů v zápatí",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_footer_links_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva odkazů v navigaci v záhlaví",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_header_menu_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva aktivních odkazů v navigaci v záhlaví",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_active_header_menu_color",
		"type" => "color",
		"std" => "#"),
    
  // Other objects colors    
  array( "name" => "Barvy dalších objektů",
		"type" => "heading",
		"icon" => "layout"),
    
  array( "name" => "Barva pozadí hlavní obsahové části",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_content_background_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva horního a dolního orámování hlavní obsahové části",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_content_border_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva podtržení v navigaci v záhlaví",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_menu_underline_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva horního orámování rozbalovacích podnabídek",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_menu_border_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barva pozadí data ve výpisu příspěvků",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_post_entry_background_color",
		"type" => "color",
		"std" => "#"),
    
  array( "name" => "Barevný přechod vyhledávacího a rolovacího boxu",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_gradient_darkest_color",
		"type" => "color",
		"std" => "#"),
    
  array( "desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_gradient_middle_color",
		"type" => "color",
		"std" => "#"),
    
  array( "desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_gradient_lightest_color",
		"type" => "color",
		"std" => "#"),	
	
	array( "name" => "tab_content_3",
		"type" => "tabcontent-close",
		"icon" => "layout"),
// Close Color settings

// Open Fonts
array( "name" => "tab_content_4",
		"type" => "tabcontent-open",
		"display" => "none",
		"icon" => "layout"),

	array( "name" => "Písma",
		"type" => "heading",
		"icon" => "layout"),

	array( "name"=>"Font celého webu",
		"desc" => "Vyberte společný font pro všechny zobrazené texty.",
		"id" => $visitpress_shortname."_body_google_fonts",
		"std" => "",
		"class" => "hidden",
		"options" => array(
			'' => 'default',
      'Arimo' => 'Arimo',	
			'Droid Serif' => 'Droid Serif',
			'Abel' => 'Abel',			
			'Aclonica' => 'Aclonica',
			'Actor' => 'Actor',
			'Adamina' => 'Adamina',
			'Aldrich' => 'Aldrich',
			'Alice' => 'Alice',
			'Alike' => 'Alike',
			'Allan' => 'Allan',
			'Andika' => 'Andika',
			'Antic' => 'Antic',
			'Allerta' => 'Allerta',
			'Amaranth' => 'Amaranth',
			'Arimo' => 'Arimo',	
			'Artifika' => 'Artifika',
			'Arvo' => 'Arvo',
			'Brawler' => 'Brawler',
			'Buda:light' => 'Buda',		
			'Cantarell' => 'Cantarell',					
			'Chivo' => 'Chivo',			
			'Coda' => 'Coda',			
			'Copse' => 'Copse',
			'Corben:bold' => 'Corben',
			'Cousine' => 'Cousine',			
			'Coustard' => 'Coustard',
			'Covered By Your Grace' => 'Covered By Your Grace',
			'Crafty Girls' => 'Crafty Girls',
			'Crimson Text' => 'Crimson Text',
			'Crushed' => 'Crushed',
			'Cuprum' => 'Cuprum',
			'Damion' => 'Damion',
			'Dancing Script' => 'Dancing Script',
			'Dawning of a New Day' => 'Dawning of a New Day',
			'Days One' => 'Days One',
			'Delius' => 'Delius',
			'Delius Swash Caps' => 'Delius Swash Caps',
			'Delius Unicase' => 'Delius Unicase',
			'Didact Gothic' => 'Didact Gothic',
			'Dorsa' => 'Dorsa',
			'Droid Sans' => 'Droid Sans',
			'Droid Sans Mono' => 'Droid Sans Mono',
			'EB Garamond' => 'EB Garamond',
			'Expletus Sans' => 'Expletus Sans',
			'Fanwood Text' => 'Fanwood Text',
			'Federo' => 'Federo',
			'Fontdiner Swanky' => 'Fontdiner Swanky',
			'Forum' => 'Forum',
			'Francois One' => 'Francois One',
			'Gentium Basic' => 'Gentium Basic',
			'Gentium Book Basic' => 'Gentium Book Basic',
			'Geo' => 'Geo',
			'Geostar' => 'Geostar',
			'Geostar Fill' => 'Geostar Fill',
			'Give You Glory' => 'Give You Glory',
			'Gloria Hallelujah' => 'Gloria Hallelujah',
			'Goblin One' => 'Goblin One',
			'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
			'Gravitas One' => 'Gravitas One',
			'Gruppo' => 'Gruppo',
			'Hammersmith One' => 'Hammersmith One',
			'Holtwood One SC' => 'Holtwood One SC',
			'Homemade Apple' => 'Homemade Apple',
			'Inconsolata' => 'Inconsolata',
			'Indie Flower' => 'Indie Flower',
			'IM Fell DW Pica' => 'IM Fell DW Pica',
			'Irish Grover' => 'Irish Grover',
			'Irish Growler' => 'Irish Growler',
			'Istok Web' => 'Istok Web',
			'Judson' => 'Judson',
			'Julee' => 'Julee',
			'Jura:light' => ' Jura Light',
			'Jura' => ' Jura Regular',
			'Just Another Hand' => 'Just Another Hand',
			'Just Me Again Down Here' => 'Just Me Again Down Here',
			'Kameron' => 'Kameron',
			'Kelly Slab' => 'Kelly Slab',
			'Kenia' => 'Kenia',
			'Kranky' => 'Kranky',
			'Kreon' => 'Kreon',
			'Kristi' => 'Kristi',
			'La Belle Aurore' => 'La Belle Aurore',
			'League Script' => 'League Script',
			'Leckerli One' => 'Leckerli One',
			'Lekton' => ' Lekton',
			'Limelight' => ' Limelight',
			'Lobster' => 'Lobster',
			'Lobster Two' => 'Lobster Two',
			'Lora' => 'Lora',
			'Love Ya Like A Sister' => 'Love Ya Like A Sister',
			'Loved by the King' => 'Loved by the King',
			'Luckiest Guy' => 'Luckiest Guy',
			'Maiden Orange' => 'Maiden Orange',
			'Mako' => 'Mako',
			'Marvel' => 'Marvel',
			'Maven Pro' => ' Maven Pro',
			'Meddon' => 'Meddon',
			'MedievalSharp' => 'MedievalSharp',
			'Megrim' => 'Megrim',
			'Merienda One' => 'Merienda One',
			'Merriweather' => 'Merriweather',
			'Metrophobic' => 'Metrophobic',
			'Michroma' => 'Michroma',
			'Miltonian Tattoo' => 'Miltonian Tattoo',
			'Miltonian' => 'Miltonian',
			'Modern Antiqua' => 'Modern Antiqua',
			'Monofett' => 'Monofett',
			'Molengo' => 'Molengo',
			'Monoton' => 'Monoton',
			'Montez' => 'Montez',
			'Mountains of Christmas' => 'Mountains of Christmas',
			'Muli:light' => 'Muli Light',
			'Muli' => 'Muli Regular',
			'Neucha' => 'Neucha',
			'Neuton' => 'Neuton',
			'News Cycle' => 'News Cycle',
			'Nixie One' => 'Nixie One',
			'Nobile' => 'Nobile',
			'Nova Cut' => 'Nova Cut',
			'Nova Flat' => 'Nova Flat',
			'Nova Mono' => 'Nova Mono',
			'Nova Oval' => 'Nova Oval',
			'Nova Round' => 'Nova Round',
			'Nova Script' => 'Nova Script',
			'Nova Slim' => 'Nova Slim',
			'Nova Square' => 'Nova Square',
			'Numans' => 'Numans',
			'Nunito:light' => ' Nunito Light',
			'Nunito' => ' Nunito Regular',
			'Oswald' => 'Oswald',
			'Over the Rainbow' => 'Over the Rainbow',
			'Ovo' => 'Ovo',
			'Reenie Beanie' => 'Reenie Beanie',
			'Pacifico' => 'Pacifico',
			'Passero One' => 'Passero One',
			'Patrick Hand' => 'Patrick Hand',
			'Paytone One' => 'Paytone One',
			'Permanent Marker' => 'Permanent Marker',
			'Philosopher' => 'Philosopher',
			'Play' => 'Play',
			'Playfair Display' => ' Playfair Display',
			'Podkova' => ' Podkova',
			'Poller One' => 'Poller One',
			'Pompiere' => 'Pompiere',
			'Prata' => 'Prata',
			'Prociono' => 'Prociono',
			'PT Sans' => 'PT Sans',
			'PT Sans Caption' => 'PT Sans Caption',
			'PT Sans Narrow' => 'PT Sans Narrow',
			'PT Serif' => 'PT Serif',
			'PT Serif Caption' => 'PT Serif Caption',
			'Puritan' => 'Puritan',
			'Quattrocento' => 'Quattrocento',
			'Quattrocento Sans' => 'Quattrocento Sans',
			'Questrial' => 'Questrial',
			'Radley' => 'Radley',
			'Raleway:100' => 'Raleway',
			'Rationale' => 'Rationale',
			'Redressed' => 'Redressed',
			'Rock Salt' => 'Rock Salt',
			'Rochester' => 'Rochester',
			'Rokkitt' => 'Rokkitt',
			'Rosario' => 'Rosario',
			'Ruslan Display' => 'Ruslan Display',
			'Sansita One' => 'Sansita One',
			'Schoolbell' => 'Schoolbell',
			'Shadows Into Light' => 'Shadows Into Light',
			'Shanti' => 'Shanti',
			'Short Stack' => 'Short Stack',
			'Sigmar One' => 'Sigmar One',
			'Six Caps' => 'Six Caps',
			'Slackey' => 'Slackey',
			'Smokum' => 'Smokum',
			'Smythe' => 'Smythe',
			'Sniglet:800' => 'Sniglet',
			'Snippet' => 'Snippet',
			'Sorts Mill Goudy' => 'Sorts Mill Goudy',
			'Special Elite' => 'Special Elite',
			'Spinnaker' => 'Spinnaker',
			'Stardos Stencil' => 'Stardos Stencil',
			'Sue Ellen Francisco' => 'Sue Ellen Francisco',
			'Sunshiney' => 'Sunshiney',
			'Swanky and Moo Moo' => 'Swanky and Moo Moo',
			'Syncopate' => 'Syncopate',
			'Tangerine' => 'Tangerine',
			'Tenor Sans' => ' Tenor Sans',
			'Terminal Dosis Light' => 'Terminal Dosis Light',
			'Tinos' => 'Tinos',
			'Tulpen One' => 'Tulpen One',
			'Ubuntu' => 'Ubuntu',
			'Ultra' => 'Ultra',
			'Unna' => 'Unna',
			'Unkempt' => 'Unkempt',
			'UnifrakturCook:bold' => 'UnifrakturCook',
			'UnifrakturMaguntia' => 'UnifrakturMaguntia',
			'Varela' => 'Varela',
			'Varela Round' => 'Varela Round',
			'Vibur' => 'Vibur',
			'Vidaloka' => 'Vidaloka',
			'Volkhov' => 'Volkhov',
			'Vollkorn' => 'Vollkorn',
			'Voltaire' => 'Voltaire',
			'VT323' => 'VT323',
			'Waiting for the Sunrise' => 'Waiting for the Sunrise',
			'Wallpoet' => 'Wallpoet',
			'Walter Turncoat' => 'Walter Turncoat',
			'Wire One' => 'Wire One',
			'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
			'Yellowtail' => 'Yellowtail',
			'Yeseva One' => 'Yeseva One',
			'Zeyada' => 'Zeyada'),
		"type" => "select"),


	array( "name"=>"Font nadpisu webu",
		"desc" => "Vyberte font pro nadpis v záhlaví Vašeho webu.",
		"id" => $visitpress_shortname."_headings_google_fonts",
		"std" => "",
		"class" => "hidden",
		"options" => array(
      '' => 'default',
			'Kaushan Script' => 'Kaushan Script',
			'Droid Serif' => 'Droid Serif',
			'Abel' => 'Abel',
			'Aclonica' => 'Aclonica',
			'Actor' => 'Actor',
			'Adamina' => 'Adamina',
			'Aldrich' => 'Aldrich',
			'Alice' => 'Alice',
			'Alike' => 'Alike',
			'Allan' => 'Allan',
			'Andika' => 'Andika',
			'Antic' => 'Antic',
			'Allerta' => 'Allerta',
			'Amaranth' => 'Amaranth',
			'Arimo' => 'Arimo',	
			'Artifika' => 'Artifika',
			'Arvo' => 'Arvo',
			'Brawler' => 'Brawler',
			'Buda:light' => 'Buda',		
			'Cantarell' => 'Cantarell',					
			'Chivo' => 'Chivo',			
			'Coda' => 'Coda',			
			'Copse' => 'Copse',
			'Corben:bold' => 'Corben',
			'Cousine' => 'Cousine',			
			'Coustard' => 'Coustard',
			'Covered By Your Grace' => 'Covered By Your Grace',
			'Crafty Girls' => 'Crafty Girls',
			'Crimson Text' => 'Crimson Text',
			'Crushed' => 'Crushed',
			'Cuprum' => 'Cuprum',
			'Damion' => 'Damion',
			'Dancing Script' => 'Dancing Script',
			'Dawning of a New Day' => 'Dawning of a New Day',
			'Days One' => 'Days One',
			'Delius' => 'Delius',
			'Delius Swash Caps' => 'Delius Swash Caps',
			'Delius Unicase' => 'Delius Unicase',
			'Didact Gothic' => 'Didact Gothic',
			'Dorsa' => 'Dorsa',
			'Droid Sans' => 'Droid Sans',
			'Droid Sans Mono' => 'Droid Sans Mono',
			'EB Garamond' => 'EB Garamond',
			'Expletus Sans' => 'Expletus Sans',
			'Fanwood Text' => 'Fanwood Text',
			'Federo' => 'Federo',
			'Fontdiner Swanky' => 'Fontdiner Swanky',
			'Forum' => 'Forum',
			'Francois One' => 'Francois One',
			'Gentium Basic' => 'Gentium Basic',
			'Gentium Book Basic' => 'Gentium Book Basic',
			'Geo' => 'Geo',
			'Geostar' => 'Geostar',
			'Geostar Fill' => 'Geostar Fill',
			'Give You Glory' => 'Give You Glory',
			'Gloria Hallelujah' => 'Gloria Hallelujah',
			'Goblin One' => 'Goblin One',
			'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
			'Gravitas One' => 'Gravitas One',
			'Gruppo' => 'Gruppo',
			'Hammersmith One' => 'Hammersmith One',
			'Holtwood One SC' => 'Holtwood One SC',
			'Homemade Apple' => 'Homemade Apple',
			'Inconsolata' => 'Inconsolata',
			'Indie Flower' => 'Indie Flower',
			'IM Fell DW Pica' => 'IM Fell DW Pica',
			'Irish Grover' => 'Irish Grover',
			'Irish Growler' => 'Irish Growler',
			'Istok Web' => 'Istok Web',
			'Judson' => 'Judson',
			'Julee' => 'Julee',
			'Jura:light' => ' Jura Light',
			'Jura' => ' Jura Regular',
			'Just Another Hand' => 'Just Another Hand',
			'Just Me Again Down Here' => 'Just Me Again Down Here',
			'Kameron' => 'Kameron',
			'Kelly Slab' => 'Kelly Slab',
			'Kenia' => 'Kenia',
			'Kranky' => 'Kranky',
			'Kreon' => 'Kreon',
			'Kristi' => 'Kristi',
			'La Belle Aurore' => 'La Belle Aurore',
			'League Script' => 'League Script',
			'Leckerli One' => 'Leckerli One',
			'Lekton' => ' Lekton',
			'Limelight' => ' Limelight',
			'Lobster' => 'Lobster',
			'Lobster Two' => 'Lobster Two',
			'Lora' => 'Lora',
			'Love Ya Like A Sister' => 'Love Ya Like A Sister',
			'Loved by the King' => 'Loved by the King',
			'Luckiest Guy' => 'Luckiest Guy',
			'Maiden Orange' => 'Maiden Orange',
			'Mako' => 'Mako',
			'Marvel' => 'Marvel',
			'Maven Pro' => ' Maven Pro',
			'Meddon' => 'Meddon',
			'MedievalSharp' => 'MedievalSharp',
			'Megrim' => 'Megrim',
			'Merienda One' => 'Merienda One',
			'Merriweather' => 'Merriweather',
			'Metrophobic' => 'Metrophobic',
			'Michroma' => 'Michroma',
			'Miltonian Tattoo' => 'Miltonian Tattoo',
			'Miltonian' => 'Miltonian',
			'Modern Antiqua' => 'Modern Antiqua',
			'Monofett' => 'Monofett',
			'Molengo' => 'Molengo',
			'Monoton' => 'Monoton',
			'Montez' => 'Montez',
			'Mountains of Christmas' => 'Mountains of Christmas',
			'Muli:light' => 'Muli Light',
			'Muli' => 'Muli Regular',
			'Neucha' => 'Neucha',
			'Neuton' => 'Neuton',
			'News Cycle' => 'News Cycle',
			'Nixie One' => 'Nixie One',
			'Nobile' => 'Nobile',
			'Nova Cut' => 'Nova Cut',
			'Nova Flat' => 'Nova Flat',
			'Nova Mono' => 'Nova Mono',
			'Nova Oval' => 'Nova Oval',
			'Nova Round' => 'Nova Round',
			'Nova Script' => 'Nova Script',
			'Nova Slim' => 'Nova Slim',
			'Nova Square' => 'Nova Square',
			'Numans' => 'Numans',
			'Nunito:light' => ' Nunito Light',
			'Nunito' => ' Nunito Regular',
			'Oswald' => 'Oswald',
			'Over the Rainbow' => 'Over the Rainbow',
			'Ovo' => 'Ovo',
			'Reenie Beanie' => 'Reenie Beanie',
			'Pacifico' => 'Pacifico',
			'Passero One' => 'Passero One',
			'Patrick Hand' => 'Patrick Hand',
			'Paytone One' => 'Paytone One',
			'Permanent Marker' => 'Permanent Marker',
			'Philosopher' => 'Philosopher',
			'Play' => 'Play',
			'Playfair Display' => ' Playfair Display',
			'Podkova' => ' Podkova',
			'Poller One' => 'Poller One',
			'Pompiere' => 'Pompiere',
			'Prata' => 'Prata',
			'Prociono' => 'Prociono',
			'PT Sans' => 'PT Sans',
			'PT Sans Caption' => 'PT Sans Caption',
			'PT Sans Narrow' => 'PT Sans Narrow',
			'PT Serif' => 'PT Serif',
			'PT Serif Caption' => 'PT Serif Caption',
			'Puritan' => 'Puritan',
			'Quattrocento' => 'Quattrocento',
			'Quattrocento Sans' => 'Quattrocento Sans',
			'Questrial' => 'Questrial',
			'Radley' => 'Radley',
			'Raleway:100' => 'Raleway',
			'Rationale' => 'Rationale',
			'Redressed' => 'Redressed',
			'Rock Salt' => 'Rock Salt',
			'Rochester' => 'Rochester',
			'Rokkitt' => 'Rokkitt',
			'Rosario' => 'Rosario',
			'Ruslan Display' => 'Ruslan Display',
			'Sansita One' => 'Sansita One',
			'Schoolbell' => 'Schoolbell',
			'Shadows Into Light' => 'Shadows Into Light',
			'Shanti' => 'Shanti',
			'Short Stack' => 'Short Stack',
			'Sigmar One' => 'Sigmar One',
			'Six Caps' => 'Six Caps',
			'Slackey' => 'Slackey',
			'Smokum' => 'Smokum',
			'Smythe' => 'Smythe',
			'Sniglet:800' => 'Sniglet',
			'Snippet' => 'Snippet',
			'Sorts Mill Goudy' => 'Sorts Mill Goudy',
			'Special Elite' => 'Special Elite',
			'Spinnaker' => 'Spinnaker',
			'Stardos Stencil' => 'Stardos Stencil',
			'Sue Ellen Francisco' => 'Sue Ellen Francisco',
			'Sunshiney' => 'Sunshiney',
			'Swanky and Moo Moo' => 'Swanky and Moo Moo',
			'Syncopate' => 'Syncopate',
			'Tangerine' => 'Tangerine',
			'Tenor Sans' => ' Tenor Sans',
			'Terminal Dosis Light' => 'Terminal Dosis Light',
			'Tinos' => 'Tinos',
			'Tulpen One' => 'Tulpen One',
			'Ubuntu' => 'Ubuntu',
			'Ultra' => 'Ultra',
			'Unna' => 'Unna',
			'Unkempt' => 'Unkempt',
			'UnifrakturCook:bold' => 'UnifrakturCook',
			'UnifrakturMaguntia' => 'UnifrakturMaguntia',
			'Varela' => 'Varela',
			'Varela Round' => 'Varela Round',
			'Vibur' => 'Vibur',
			'Vidaloka' => 'Vidaloka',
			'Volkhov' => 'Volkhov',
			'Vollkorn' => 'Vollkorn',
			'Voltaire' => 'Voltaire',
			'VT323' => 'VT323',
			'Waiting for the Sunrise' => 'Waiting for the Sunrise',
			'Wallpoet' => 'Wallpoet',
			'Walter Turncoat' => 'Walter Turncoat',
			'Wire One' => 'Wire One',
			'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
			'Yellowtail' => 'Yellowtail',
			'Yeseva One' => 'Yeseva One',
			'Zeyada' => 'Zeyada'),
		"type" => "select"),	

	array( "name" => "Font popisu webu",
		"desc" => "Vyberte font pro popis Vašeho webu v záhlaví.",
		"id" => $visitpress_shortname."_description_google_fonts",
		"std" => "",
		"class" => "hidden",
		"options" => array(
			'' => 'default',
      'Arimo' => 'Arimo',			   
			'Droid Serif' => 'Droid Serif',
			'Abel' => 'Abel',
			'Aclonica' => 'Aclonica',
			'Actor' => 'Actor',
			'Adamina' => 'Adamina',
			'Aldrich' => 'Aldrich',
			'Alice' => 'Alice',
			'Alike' => 'Alike',
			'Allan' => 'Allan',
			'Andika' => 'Andika',
			'Antic' => 'Antic',
			'Allerta' => 'Allerta',
			'Amaranth' => 'Amaranth',
			'Artifika' => 'Artifika',
			'Arvo' => 'Arvo',
			'Brawler' => 'Brawler',
			'Buda:light' => 'Buda',		
			'Cantarell' => 'Cantarell',					
			'Chivo' => 'Chivo',			
			'Coda' => 'Coda',			
			'Copse' => 'Copse',
			'Corben:bold' => 'Corben',
			'Cousine' => 'Cousine',			
			'Coustard' => 'Coustard',
			'Covered By Your Grace' => 'Covered By Your Grace',
			'Crafty Girls' => 'Crafty Girls',
			'Crimson Text' => 'Crimson Text',
			'Crushed' => 'Crushed',
			'Cuprum' => 'Cuprum',
			'Damion' => 'Damion',
			'Dancing Script' => 'Dancing Script',
			'Dawning of a New Day' => 'Dawning of a New Day',
			'Days One' => 'Days One',
			'Delius' => 'Delius',
			'Delius Swash Caps' => 'Delius Swash Caps',
			'Delius Unicase' => 'Delius Unicase',
			'Didact Gothic' => 'Didact Gothic',
			'Dorsa' => 'Dorsa',
			'Droid Sans' => 'Droid Sans',
			'Droid Sans Mono' => 'Droid Sans Mono',
			'EB Garamond' => 'EB Garamond',
			'Expletus Sans' => 'Expletus Sans',
			'Fanwood Text' => 'Fanwood Text',
			'Federo' => 'Federo',
			'Fontdiner Swanky' => 'Fontdiner Swanky',
			'Forum' => 'Forum',
			'Francois One' => 'Francois One',
			'Gentium Basic' => 'Gentium Basic',
			'Gentium Book Basic' => 'Gentium Book Basic',
			'Geo' => 'Geo',
			'Geostar' => 'Geostar',
			'Geostar Fill' => 'Geostar Fill',
			'Give You Glory' => 'Give You Glory',
			'Gloria Hallelujah' => 'Gloria Hallelujah',
			'Goblin One' => 'Goblin One',
			'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
			'Gravitas One' => 'Gravitas One',
			'Gruppo' => 'Gruppo',
			'Hammersmith One' => 'Hammersmith One',
			'Holtwood One SC' => 'Holtwood One SC',
			'Homemade Apple' => 'Homemade Apple',
			'Inconsolata' => 'Inconsolata',
			'Indie Flower' => 'Indie Flower',
			'IM Fell DW Pica' => 'IM Fell DW Pica',
			'Irish Grover' => 'Irish Grover',
			'Irish Growler' => 'Irish Growler',
			'Istok Web' => 'Istok Web',
			'Judson' => 'Judson',
			'Julee' => 'Julee',
			'Jura:light' => ' Jura Light',
			'Jura' => ' Jura Regular',
			'Just Another Hand' => 'Just Another Hand',
			'Just Me Again Down Here' => 'Just Me Again Down Here',
			'Kameron' => 'Kameron',
			'Kelly Slab' => 'Kelly Slab',
			'Kenia' => 'Kenia',
			'Kranky' => 'Kranky',
			'Kreon' => 'Kreon',
			'Kristi' => 'Kristi',
			'La Belle Aurore' => 'La Belle Aurore',
			'League Script' => 'League Script',
			'Leckerli One' => 'Leckerli One',
			'Lekton' => ' Lekton',
			'Limelight' => ' Limelight',
			'Lobster' => 'Lobster',
			'Lobster Two' => 'Lobster Two',
			'Lora' => 'Lora',
			'Love Ya Like A Sister' => 'Love Ya Like A Sister',
			'Loved by the King' => 'Loved by the King',
			'Luckiest Guy' => 'Luckiest Guy',
			'Maiden Orange' => 'Maiden Orange',
			'Mako' => 'Mako',
			'Marvel' => 'Marvel',
			'Maven Pro' => ' Maven Pro',
			'Meddon' => 'Meddon',
			'MedievalSharp' => 'MedievalSharp',
			'Megrim' => 'Megrim',
			'Merienda One' => 'Merienda One',
			'Merriweather' => 'Merriweather',
			'Metrophobic' => 'Metrophobic',
			'Michroma' => 'Michroma',
			'Miltonian Tattoo' => 'Miltonian Tattoo',
			'Miltonian' => 'Miltonian',
			'Modern Antiqua' => 'Modern Antiqua',
			'Monofett' => 'Monofett',
			'Molengo' => 'Molengo',
			'Monoton' => 'Monoton',
			'Montez' => 'Montez',
			'Mountains of Christmas' => 'Mountains of Christmas',
			'Muli:light' => 'Muli Light',
			'Muli' => 'Muli Regular',
			'Neucha' => 'Neucha',
			'Neuton' => 'Neuton',
			'News Cycle' => 'News Cycle',
			'Nixie One' => 'Nixie One',
			'Nobile' => 'Nobile',
			'Nova Cut' => 'Nova Cut',
			'Nova Flat' => 'Nova Flat',
			'Nova Mono' => 'Nova Mono',
			'Nova Oval' => 'Nova Oval',
			'Nova Round' => 'Nova Round',
			'Nova Script' => 'Nova Script',
			'Nova Slim' => 'Nova Slim',
			'Nova Square' => 'Nova Square',
			'Numans' => 'Numans',
			'Nunito:light' => ' Nunito Light',
			'Nunito' => ' Nunito Regular',
			'Oswald' => 'Oswald',
			'Over the Rainbow' => 'Over the Rainbow',
			'Ovo' => 'Ovo',
			'Reenie Beanie' => 'Reenie Beanie',
			'Pacifico' => 'Pacifico',
			'Passero One' => 'Passero One',
			'Patrick Hand' => 'Patrick Hand',
			'Paytone One' => 'Paytone One',
			'Permanent Marker' => 'Permanent Marker',
			'Philosopher' => 'Philosopher',
			'Play' => 'Play',
			'Playfair Display' => ' Playfair Display',
			'Podkova' => ' Podkova',
			'Poller One' => 'Poller One',
			'Pompiere' => 'Pompiere',
			'Prata' => 'Prata',
			'Prociono' => 'Prociono',
			'PT Sans' => 'PT Sans',
			'PT Sans Caption' => 'PT Sans Caption',
			'PT Sans Narrow' => 'PT Sans Narrow',
			'PT Serif' => 'PT Serif',
			'PT Serif Caption' => 'PT Serif Caption',
			'Puritan' => 'Puritan',
			'Quattrocento' => 'Quattrocento',
			'Quattrocento Sans' => 'Quattrocento Sans',
			'Questrial' => 'Questrial',
			'Radley' => 'Radley',
			'Raleway:100' => 'Raleway',
			'Rationale' => 'Rationale',
			'Redressed' => 'Redressed',
			'Rock Salt' => 'Rock Salt',
			'Rochester' => 'Rochester',
			'Rokkitt' => 'Rokkitt',
			'Rosario' => 'Rosario',
			'Ruslan Display' => 'Ruslan Display',
			'Sansita One' => 'Sansita One',
			'Schoolbell' => 'Schoolbell',
			'Shadows Into Light' => 'Shadows Into Light',
			'Shanti' => 'Shanti',
			'Short Stack' => 'Short Stack',
			'Sigmar One' => 'Sigmar One',
			'Six Caps' => 'Six Caps',
			'Slackey' => 'Slackey',
			'Smokum' => 'Smokum',
			'Smythe' => 'Smythe',
			'Sniglet:800' => 'Sniglet',
			'Snippet' => 'Snippet',
			'Sorts Mill Goudy' => 'Sorts Mill Goudy',
			'Special Elite' => 'Special Elite',
			'Spinnaker' => 'Spinnaker',
			'Stardos Stencil' => 'Stardos Stencil',
			'Sue Ellen Francisco' => 'Sue Ellen Francisco',
			'Sunshiney' => 'Sunshiney',
			'Swanky and Moo Moo' => 'Swanky and Moo Moo',
			'Syncopate' => 'Syncopate',
			'Tangerine' => 'Tangerine',
			'Tenor Sans' => ' Tenor Sans',
			'Terminal Dosis Light' => 'Terminal Dosis Light',
			'Tinos' => 'Tinos',
			'Tulpen One' => 'Tulpen One',
			'Ubuntu' => 'Ubuntu',
			'Ultra' => 'Ultra',
			'Unna' => 'Unna',
			'Unkempt' => 'Unkempt',
			'UnifrakturCook:bold' => 'UnifrakturCook',
			'UnifrakturMaguntia' => 'UnifrakturMaguntia',
			'Varela' => 'Varela',
			'Varela Round' => 'Varela Round',
			'Vibur' => 'Vibur',
			'Vidaloka' => 'Vidaloka',
			'Volkhov' => 'Volkhov',
			'Vollkorn' => 'Vollkorn',
			'Voltaire' => 'Voltaire',
			'VT323' => 'VT323',
			'Waiting for the Sunrise' => 'Waiting for the Sunrise',
			'Wallpoet' => 'Wallpoet',
			'Walter Turncoat' => 'Walter Turncoat',
			'Wire One' => 'Wire One',
			'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
			'Yellowtail' => 'Yellowtail',
			'Yeseva One' => 'Yeseva One',
			'Zeyada' => 'Zeyada'),
		"type" => "select"),
    
  array( "name" => "Font nadpisů stránek/příspěvků",
		"desc" => "Vyberte font pro nadpisy stránek/příspěvků (nadpisy h1 - h6).",
		"id" => $visitpress_shortname."_headline_google_fonts",
		"std" => "",
		"class" => "hidden",
		"options" => array(
			'' => 'default',
      'Arimo' => 'Arimo',			   
			'Droid Serif' => 'Droid Serif',
			'Abel' => 'Abel',
			'Aclonica' => 'Aclonica',
			'Actor' => 'Actor',
			'Adamina' => 'Adamina',
			'Aldrich' => 'Aldrich',
			'Alice' => 'Alice',
			'Alike' => 'Alike',
			'Allan' => 'Allan',
			'Andika' => 'Andika',
			'Antic' => 'Antic',
			'Allerta' => 'Allerta',
			'Amaranth' => 'Amaranth',
			'Artifika' => 'Artifika',
			'Arvo' => 'Arvo',
			'Brawler' => 'Brawler',
			'Buda:light' => 'Buda',		
			'Cantarell' => 'Cantarell',					
			'Chivo' => 'Chivo',			
			'Coda' => 'Coda',			
			'Copse' => 'Copse',
			'Corben:bold' => 'Corben',
			'Cousine' => 'Cousine',			
			'Coustard' => 'Coustard',
			'Covered By Your Grace' => 'Covered By Your Grace',
			'Crafty Girls' => 'Crafty Girls',
			'Crimson Text' => 'Crimson Text',
			'Crushed' => 'Crushed',
			'Cuprum' => 'Cuprum',
			'Damion' => 'Damion',
			'Dancing Script' => 'Dancing Script',
			'Dawning of a New Day' => 'Dawning of a New Day',
			'Days One' => 'Days One',
			'Delius' => 'Delius',
			'Delius Swash Caps' => 'Delius Swash Caps',
			'Delius Unicase' => 'Delius Unicase',
			'Didact Gothic' => 'Didact Gothic',
			'Dorsa' => 'Dorsa',
			'Droid Sans' => 'Droid Sans',
			'Droid Sans Mono' => 'Droid Sans Mono',
			'EB Garamond' => 'EB Garamond',
			'Expletus Sans' => 'Expletus Sans',
			'Fanwood Text' => 'Fanwood Text',
			'Federo' => 'Federo',
			'Fontdiner Swanky' => 'Fontdiner Swanky',
			'Forum' => 'Forum',
			'Francois One' => 'Francois One',
			'Gentium Basic' => 'Gentium Basic',
			'Gentium Book Basic' => 'Gentium Book Basic',
			'Geo' => 'Geo',
			'Geostar' => 'Geostar',
			'Geostar Fill' => 'Geostar Fill',
			'Give You Glory' => 'Give You Glory',
			'Gloria Hallelujah' => 'Gloria Hallelujah',
			'Goblin One' => 'Goblin One',
			'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
			'Gravitas One' => 'Gravitas One',
			'Gruppo' => 'Gruppo',
			'Hammersmith One' => 'Hammersmith One',
			'Holtwood One SC' => 'Holtwood One SC',
			'Homemade Apple' => 'Homemade Apple',
			'Inconsolata' => 'Inconsolata',
			'Indie Flower' => 'Indie Flower',
			'IM Fell DW Pica' => 'IM Fell DW Pica',
			'Irish Grover' => 'Irish Grover',
			'Irish Growler' => 'Irish Growler',
			'Istok Web' => 'Istok Web',
			'Judson' => 'Judson',
			'Julee' => 'Julee',
			'Jura:light' => ' Jura Light',
			'Jura' => ' Jura Regular',
			'Just Another Hand' => 'Just Another Hand',
			'Just Me Again Down Here' => 'Just Me Again Down Here',
			'Kameron' => 'Kameron',
			'Kelly Slab' => 'Kelly Slab',
			'Kenia' => 'Kenia',
			'Kranky' => 'Kranky',
			'Kreon' => 'Kreon',
			'Kristi' => 'Kristi',
			'La Belle Aurore' => 'La Belle Aurore',
			'League Script' => 'League Script',
			'Leckerli One' => 'Leckerli One',
			'Lekton' => ' Lekton',
			'Limelight' => ' Limelight',
			'Lobster' => 'Lobster',
			'Lobster Two' => 'Lobster Two',
			'Lora' => 'Lora',
			'Love Ya Like A Sister' => 'Love Ya Like A Sister',
			'Loved by the King' => 'Loved by the King',
			'Luckiest Guy' => 'Luckiest Guy',
			'Maiden Orange' => 'Maiden Orange',
			'Mako' => 'Mako',
			'Marvel' => 'Marvel',
			'Maven Pro' => ' Maven Pro',
			'Meddon' => 'Meddon',
			'MedievalSharp' => 'MedievalSharp',
			'Megrim' => 'Megrim',
			'Merienda One' => 'Merienda One',
			'Merriweather' => 'Merriweather',
			'Metrophobic' => 'Metrophobic',
			'Michroma' => 'Michroma',
			'Miltonian Tattoo' => 'Miltonian Tattoo',
			'Miltonian' => 'Miltonian',
			'Modern Antiqua' => 'Modern Antiqua',
			'Monofett' => 'Monofett',
			'Molengo' => 'Molengo',
			'Monoton' => 'Monoton',
			'Montez' => 'Montez',
			'Mountains of Christmas' => 'Mountains of Christmas',
			'Muli:light' => 'Muli Light',
			'Muli' => 'Muli Regular',
			'Neucha' => 'Neucha',
			'Neuton' => 'Neuton',
			'News Cycle' => 'News Cycle',
			'Nixie One' => 'Nixie One',
			'Nobile' => 'Nobile',
			'Nova Cut' => 'Nova Cut',
			'Nova Flat' => 'Nova Flat',
			'Nova Mono' => 'Nova Mono',
			'Nova Oval' => 'Nova Oval',
			'Nova Round' => 'Nova Round',
			'Nova Script' => 'Nova Script',
			'Nova Slim' => 'Nova Slim',
			'Nova Square' => 'Nova Square',
			'Numans' => 'Numans',
			'Nunito:light' => ' Nunito Light',
			'Nunito' => ' Nunito Regular',
			'Oswald' => 'Oswald',
			'Over the Rainbow' => 'Over the Rainbow',
			'Ovo' => 'Ovo',
			'Reenie Beanie' => 'Reenie Beanie',
			'Pacifico' => 'Pacifico',
			'Passero One' => 'Passero One',
			'Patrick Hand' => 'Patrick Hand',
			'Paytone One' => 'Paytone One',
			'Permanent Marker' => 'Permanent Marker',
			'Philosopher' => 'Philosopher',
			'Play' => 'Play',
			'Playfair Display' => ' Playfair Display',
			'Podkova' => ' Podkova',
			'Poller One' => 'Poller One',
			'Pompiere' => 'Pompiere',
			'Prata' => 'Prata',
			'Prociono' => 'Prociono',
			'PT Sans' => 'PT Sans',
			'PT Sans Caption' => 'PT Sans Caption',
			'PT Sans Narrow' => 'PT Sans Narrow',
			'PT Serif' => 'PT Serif',
			'PT Serif Caption' => 'PT Serif Caption',
			'Puritan' => 'Puritan',
			'Quattrocento' => 'Quattrocento',
			'Quattrocento Sans' => 'Quattrocento Sans',
			'Questrial' => 'Questrial',
			'Radley' => 'Radley',
			'Raleway:100' => 'Raleway',
			'Rationale' => 'Rationale',
			'Redressed' => 'Redressed',
			'Rock Salt' => 'Rock Salt',
			'Rochester' => 'Rochester',
			'Rokkitt' => 'Rokkitt',
			'Rosario' => 'Rosario',
			'Ruslan Display' => 'Ruslan Display',
			'Sansita One' => 'Sansita One',
			'Schoolbell' => 'Schoolbell',
			'Shadows Into Light' => 'Shadows Into Light',
			'Shanti' => 'Shanti',
			'Short Stack' => 'Short Stack',
			'Sigmar One' => 'Sigmar One',
			'Six Caps' => 'Six Caps',
			'Slackey' => 'Slackey',
			'Smokum' => 'Smokum',
			'Smythe' => 'Smythe',
			'Sniglet:800' => 'Sniglet',
			'Snippet' => 'Snippet',
			'Sorts Mill Goudy' => 'Sorts Mill Goudy',
			'Special Elite' => 'Special Elite',
			'Spinnaker' => 'Spinnaker',
			'Stardos Stencil' => 'Stardos Stencil',
			'Sue Ellen Francisco' => 'Sue Ellen Francisco',
			'Sunshiney' => 'Sunshiney',
			'Swanky and Moo Moo' => 'Swanky and Moo Moo',
			'Syncopate' => 'Syncopate',
			'Tangerine' => 'Tangerine',
			'Tenor Sans' => ' Tenor Sans',
			'Terminal Dosis Light' => 'Terminal Dosis Light',
			'Tinos' => 'Tinos',
			'Tulpen One' => 'Tulpen One',
			'Ubuntu' => 'Ubuntu',
			'Ultra' => 'Ultra',
			'Unna' => 'Unna',
			'Unkempt' => 'Unkempt',
			'UnifrakturCook:bold' => 'UnifrakturCook',
			'UnifrakturMaguntia' => 'UnifrakturMaguntia',
			'Varela' => 'Varela',
			'Varela Round' => 'Varela Round',
			'Vibur' => 'Vibur',
			'Vidaloka' => 'Vidaloka',
			'Volkhov' => 'Volkhov',
			'Vollkorn' => 'Vollkorn',
			'Voltaire' => 'Voltaire',
			'VT323' => 'VT323',
			'Waiting for the Sunrise' => 'Waiting for the Sunrise',
			'Wallpoet' => 'Wallpoet',
			'Walter Turncoat' => 'Walter Turncoat',
			'Wire One' => 'Wire One',
			'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
			'Yellowtail' => 'Yellowtail',
			'Yeseva One' => 'Yeseva One',
			'Zeyada' => 'Zeyada'),
		"type" => "select"),
    
  array( "name" => "Font nadpisů ve výpisu příspěvků",
		"desc" => "Vyberte font pro nadpisy ve výpisu příspěvků/výpisu archivů/výpisu výsledků vyhledávání.",
		"id" => $visitpress_shortname."_postentry_google_fonts",
		"std" => "",
		"class" => "hidden",
		"options" => array(
			'' => 'default',
      'Arimo' => 'Arimo',			   
			'Droid Serif' => 'Droid Serif',
			'Abel' => 'Abel',
			'Aclonica' => 'Aclonica',
			'Actor' => 'Actor',
			'Adamina' => 'Adamina',
			'Aldrich' => 'Aldrich',
			'Alice' => 'Alice',
			'Alike' => 'Alike',
			'Allan' => 'Allan',
			'Andika' => 'Andika',
			'Antic' => 'Antic',
			'Allerta' => 'Allerta',
			'Amaranth' => 'Amaranth',
			'Artifika' => 'Artifika',
			'Arvo' => 'Arvo',
			'Brawler' => 'Brawler',
			'Buda:light' => 'Buda',		
			'Cantarell' => 'Cantarell',					
			'Chivo' => 'Chivo',			
			'Coda' => 'Coda',			
			'Copse' => 'Copse',
			'Corben:bold' => 'Corben',
			'Cousine' => 'Cousine',			
			'Coustard' => 'Coustard',
			'Covered By Your Grace' => 'Covered By Your Grace',
			'Crafty Girls' => 'Crafty Girls',
			'Crimson Text' => 'Crimson Text',
			'Crushed' => 'Crushed',
			'Cuprum' => 'Cuprum',
			'Damion' => 'Damion',
			'Dancing Script' => 'Dancing Script',
			'Dawning of a New Day' => 'Dawning of a New Day',
			'Days One' => 'Days One',
			'Delius' => 'Delius',
			'Delius Swash Caps' => 'Delius Swash Caps',
			'Delius Unicase' => 'Delius Unicase',
			'Didact Gothic' => 'Didact Gothic',
			'Dorsa' => 'Dorsa',
			'Droid Sans' => 'Droid Sans',
			'Droid Sans Mono' => 'Droid Sans Mono',
			'EB Garamond' => 'EB Garamond',
			'Expletus Sans' => 'Expletus Sans',
			'Fanwood Text' => 'Fanwood Text',
			'Federo' => 'Federo',
			'Fontdiner Swanky' => 'Fontdiner Swanky',
			'Forum' => 'Forum',
			'Francois One' => 'Francois One',
			'Gentium Basic' => 'Gentium Basic',
			'Gentium Book Basic' => 'Gentium Book Basic',
			'Geo' => 'Geo',
			'Geostar' => 'Geostar',
			'Geostar Fill' => 'Geostar Fill',
			'Give You Glory' => 'Give You Glory',
			'Gloria Hallelujah' => 'Gloria Hallelujah',
			'Goblin One' => 'Goblin One',
			'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
			'Gravitas One' => 'Gravitas One',
			'Gruppo' => 'Gruppo',
			'Hammersmith One' => 'Hammersmith One',
			'Holtwood One SC' => 'Holtwood One SC',
			'Homemade Apple' => 'Homemade Apple',
			'Inconsolata' => 'Inconsolata',
			'Indie Flower' => 'Indie Flower',
			'IM Fell DW Pica' => 'IM Fell DW Pica',
			'Irish Grover' => 'Irish Grover',
			'Irish Growler' => 'Irish Growler',
			'Istok Web' => 'Istok Web',
			'Judson' => 'Judson',
			'Julee' => 'Julee',
			'Jura:light' => ' Jura Light',
			'Jura' => ' Jura Regular',
			'Just Another Hand' => 'Just Another Hand',
			'Just Me Again Down Here' => 'Just Me Again Down Here',
			'Kameron' => 'Kameron',
			'Kelly Slab' => 'Kelly Slab',
			'Kenia' => 'Kenia',
			'Kranky' => 'Kranky',
			'Kreon' => 'Kreon',
			'Kristi' => 'Kristi',
			'La Belle Aurore' => 'La Belle Aurore',
			'League Script' => 'League Script',
			'Leckerli One' => 'Leckerli One',
			'Lekton' => ' Lekton',
			'Limelight' => ' Limelight',
			'Lobster' => 'Lobster',
			'Lobster Two' => 'Lobster Two',
			'Lora' => 'Lora',
			'Love Ya Like A Sister' => 'Love Ya Like A Sister',
			'Loved by the King' => 'Loved by the King',
			'Luckiest Guy' => 'Luckiest Guy',
			'Maiden Orange' => 'Maiden Orange',
			'Mako' => 'Mako',
			'Marvel' => 'Marvel',
			'Maven Pro' => ' Maven Pro',
			'Meddon' => 'Meddon',
			'MedievalSharp' => 'MedievalSharp',
			'Megrim' => 'Megrim',
			'Merienda One' => 'Merienda One',
			'Merriweather' => 'Merriweather',
			'Metrophobic' => 'Metrophobic',
			'Michroma' => 'Michroma',
			'Miltonian Tattoo' => 'Miltonian Tattoo',
			'Miltonian' => 'Miltonian',
			'Modern Antiqua' => 'Modern Antiqua',
			'Monofett' => 'Monofett',
			'Molengo' => 'Molengo',
			'Monoton' => 'Monoton',
			'Montez' => 'Montez',
			'Mountains of Christmas' => 'Mountains of Christmas',
			'Muli:light' => 'Muli Light',
			'Muli' => 'Muli Regular',
			'Neucha' => 'Neucha',
			'Neuton' => 'Neuton',
			'News Cycle' => 'News Cycle',
			'Nixie One' => 'Nixie One',
			'Nobile' => 'Nobile',
			'Nova Cut' => 'Nova Cut',
			'Nova Flat' => 'Nova Flat',
			'Nova Mono' => 'Nova Mono',
			'Nova Oval' => 'Nova Oval',
			'Nova Round' => 'Nova Round',
			'Nova Script' => 'Nova Script',
			'Nova Slim' => 'Nova Slim',
			'Nova Square' => 'Nova Square',
			'Numans' => 'Numans',
			'Nunito:light' => ' Nunito Light',
			'Nunito' => ' Nunito Regular',
			'Oswald' => 'Oswald',
			'Over the Rainbow' => 'Over the Rainbow',
			'Ovo' => 'Ovo',
			'Reenie Beanie' => 'Reenie Beanie',
			'Pacifico' => 'Pacifico',
			'Passero One' => 'Passero One',
			'Patrick Hand' => 'Patrick Hand',
			'Paytone One' => 'Paytone One',
			'Permanent Marker' => 'Permanent Marker',
			'Philosopher' => 'Philosopher',
			'Play' => 'Play',
			'Playfair Display' => ' Playfair Display',
			'Podkova' => ' Podkova',
			'Poller One' => 'Poller One',
			'Pompiere' => 'Pompiere',
			'Prata' => 'Prata',
			'Prociono' => 'Prociono',
			'PT Sans' => 'PT Sans',
			'PT Sans Caption' => 'PT Sans Caption',
			'PT Sans Narrow' => 'PT Sans Narrow',
			'PT Serif' => 'PT Serif',
			'PT Serif Caption' => 'PT Serif Caption',
			'Puritan' => 'Puritan',
			'Quattrocento' => 'Quattrocento',
			'Quattrocento Sans' => 'Quattrocento Sans',
			'Questrial' => 'Questrial',
			'Radley' => 'Radley',
			'Raleway:100' => 'Raleway',
			'Rationale' => 'Rationale',
			'Redressed' => 'Redressed',
			'Rock Salt' => 'Rock Salt',
			'Rochester' => 'Rochester',
			'Rokkitt' => 'Rokkitt',
			'Rosario' => 'Rosario',
			'Ruslan Display' => 'Ruslan Display',
			'Sansita One' => 'Sansita One',
			'Schoolbell' => 'Schoolbell',
			'Shadows Into Light' => 'Shadows Into Light',
			'Shanti' => 'Shanti',
			'Short Stack' => 'Short Stack',
			'Sigmar One' => 'Sigmar One',
			'Six Caps' => 'Six Caps',
			'Slackey' => 'Slackey',
			'Smokum' => 'Smokum',
			'Smythe' => 'Smythe',
			'Sniglet:800' => 'Sniglet',
			'Snippet' => 'Snippet',
			'Sorts Mill Goudy' => 'Sorts Mill Goudy',
			'Special Elite' => 'Special Elite',
			'Spinnaker' => 'Spinnaker',
			'Stardos Stencil' => 'Stardos Stencil',
			'Sue Ellen Francisco' => 'Sue Ellen Francisco',
			'Sunshiney' => 'Sunshiney',
			'Swanky and Moo Moo' => 'Swanky and Moo Moo',
			'Syncopate' => 'Syncopate',
			'Tangerine' => 'Tangerine',
			'Tenor Sans' => ' Tenor Sans',
			'Terminal Dosis Light' => 'Terminal Dosis Light',
			'Tinos' => 'Tinos',
			'Tulpen One' => 'Tulpen One',
			'Ubuntu' => 'Ubuntu',
			'Ultra' => 'Ultra',
			'Unna' => 'Unna',
			'Unkempt' => 'Unkempt',
			'UnifrakturCook:bold' => 'UnifrakturCook',
			'UnifrakturMaguntia' => 'UnifrakturMaguntia',
			'Varela' => 'Varela',
			'Varela Round' => 'Varela Round',
			'Vibur' => 'Vibur',
			'Vidaloka' => 'Vidaloka',
			'Volkhov' => 'Volkhov',
			'Vollkorn' => 'Vollkorn',
			'Voltaire' => 'Voltaire',
			'VT323' => 'VT323',
			'Waiting for the Sunrise' => 'Waiting for the Sunrise',
			'Wallpoet' => 'Wallpoet',
			'Walter Turncoat' => 'Walter Turncoat',
			'Wire One' => 'Wire One',
			'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
			'Yellowtail' => 'Yellowtail',
			'Yeseva One' => 'Yeseva One',
			'Zeyada' => 'Zeyada'),
		"type" => "select"),
    
  array( "name" => "Font nadpisů widgetů v postranním sloupci a zápatí",
		"desc" => "Vyberte font pro nadpisy widgetů v postranním sloupci a zápatí.",
		"id" => $visitpress_shortname."_sidebar_google_fonts",
		"std" => "",
		"class" => "hidden",
		"options" => array(
			'' => 'default',
      'Arimo' => 'Arimo',			   
			'Droid Serif' => 'Droid Serif',
			'Abel' => 'Abel',
			'Aclonica' => 'Aclonica',
			'Actor' => 'Actor',
			'Adamina' => 'Adamina',
			'Aldrich' => 'Aldrich',
			'Alice' => 'Alice',
			'Alike' => 'Alike',
			'Allan' => 'Allan',
			'Andika' => 'Andika',
			'Antic' => 'Antic',
			'Allerta' => 'Allerta',
			'Amaranth' => 'Amaranth',
			'Artifika' => 'Artifika',
			'Arvo' => 'Arvo',
			'Brawler' => 'Brawler',
			'Buda:light' => 'Buda',		
			'Cantarell' => 'Cantarell',					
			'Chivo' => 'Chivo',			
			'Coda' => 'Coda',			
			'Copse' => 'Copse',
			'Corben:bold' => 'Corben',
			'Cousine' => 'Cousine',			
			'Coustard' => 'Coustard',
			'Covered By Your Grace' => 'Covered By Your Grace',
			'Crafty Girls' => 'Crafty Girls',
			'Crimson Text' => 'Crimson Text',
			'Crushed' => 'Crushed',
			'Cuprum' => 'Cuprum',
			'Damion' => 'Damion',
			'Dancing Script' => 'Dancing Script',
			'Dawning of a New Day' => 'Dawning of a New Day',
			'Days One' => 'Days One',
			'Delius' => 'Delius',
			'Delius Swash Caps' => 'Delius Swash Caps',
			'Delius Unicase' => 'Delius Unicase',
			'Didact Gothic' => 'Didact Gothic',
			'Dorsa' => 'Dorsa',
			'Droid Sans' => 'Droid Sans',
			'Droid Sans Mono' => 'Droid Sans Mono',
			'EB Garamond' => 'EB Garamond',
			'Expletus Sans' => 'Expletus Sans',
			'Fanwood Text' => 'Fanwood Text',
			'Federo' => 'Federo',
			'Fontdiner Swanky' => 'Fontdiner Swanky',
			'Forum' => 'Forum',
			'Francois One' => 'Francois One',
			'Gentium Basic' => 'Gentium Basic',
			'Gentium Book Basic' => 'Gentium Book Basic',
			'Geo' => 'Geo',
			'Geostar' => 'Geostar',
			'Geostar Fill' => 'Geostar Fill',
			'Give You Glory' => 'Give You Glory',
			'Gloria Hallelujah' => 'Gloria Hallelujah',
			'Goblin One' => 'Goblin One',
			'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
			'Gravitas One' => 'Gravitas One',
			'Gruppo' => 'Gruppo',
			'Hammersmith One' => 'Hammersmith One',
			'Holtwood One SC' => 'Holtwood One SC',
			'Homemade Apple' => 'Homemade Apple',
			'Inconsolata' => 'Inconsolata',
			'Indie Flower' => 'Indie Flower',
			'IM Fell DW Pica' => 'IM Fell DW Pica',
			'Irish Grover' => 'Irish Grover',
			'Irish Growler' => 'Irish Growler',
			'Istok Web' => 'Istok Web',
			'Judson' => 'Judson',
			'Julee' => 'Julee',
			'Jura:light' => ' Jura Light',
			'Jura' => ' Jura Regular',
			'Just Another Hand' => 'Just Another Hand',
			'Just Me Again Down Here' => 'Just Me Again Down Here',
			'Kameron' => 'Kameron',
			'Kelly Slab' => 'Kelly Slab',
			'Kenia' => 'Kenia',
			'Kranky' => 'Kranky',
			'Kreon' => 'Kreon',
			'Kristi' => 'Kristi',
			'La Belle Aurore' => 'La Belle Aurore',
			'League Script' => 'League Script',
			'Leckerli One' => 'Leckerli One',
			'Lekton' => ' Lekton',
			'Limelight' => ' Limelight',
			'Lobster' => 'Lobster',
			'Lobster Two' => 'Lobster Two',
			'Lora' => 'Lora',
			'Love Ya Like A Sister' => 'Love Ya Like A Sister',
			'Loved by the King' => 'Loved by the King',
			'Luckiest Guy' => 'Luckiest Guy',
			'Maiden Orange' => 'Maiden Orange',
			'Mako' => 'Mako',
			'Marvel' => 'Marvel',
			'Maven Pro' => ' Maven Pro',
			'Meddon' => 'Meddon',
			'MedievalSharp' => 'MedievalSharp',
			'Megrim' => 'Megrim',
			'Merienda One' => 'Merienda One',
			'Merriweather' => 'Merriweather',
			'Metrophobic' => 'Metrophobic',
			'Michroma' => 'Michroma',
			'Miltonian Tattoo' => 'Miltonian Tattoo',
			'Miltonian' => 'Miltonian',
			'Modern Antiqua' => 'Modern Antiqua',
			'Monofett' => 'Monofett',
			'Molengo' => 'Molengo',
			'Monoton' => 'Monoton',
			'Montez' => 'Montez',
			'Mountains of Christmas' => 'Mountains of Christmas',
			'Muli:light' => 'Muli Light',
			'Muli' => 'Muli Regular',
			'Neucha' => 'Neucha',
			'Neuton' => 'Neuton',
			'News Cycle' => 'News Cycle',
			'Nixie One' => 'Nixie One',
			'Nobile' => 'Nobile',
			'Nova Cut' => 'Nova Cut',
			'Nova Flat' => 'Nova Flat',
			'Nova Mono' => 'Nova Mono',
			'Nova Oval' => 'Nova Oval',
			'Nova Round' => 'Nova Round',
			'Nova Script' => 'Nova Script',
			'Nova Slim' => 'Nova Slim',
			'Nova Square' => 'Nova Square',
			'Numans' => 'Numans',
			'Nunito:light' => ' Nunito Light',
			'Nunito' => ' Nunito Regular',
			'Oswald' => 'Oswald',
			'Over the Rainbow' => 'Over the Rainbow',
			'Ovo' => 'Ovo',
			'Reenie Beanie' => 'Reenie Beanie',
			'Pacifico' => 'Pacifico',
			'Passero One' => 'Passero One',
			'Patrick Hand' => 'Patrick Hand',
			'Paytone One' => 'Paytone One',
			'Permanent Marker' => 'Permanent Marker',
			'Philosopher' => 'Philosopher',
			'Play' => 'Play',
			'Playfair Display' => ' Playfair Display',
			'Podkova' => ' Podkova',
			'Poller One' => 'Poller One',
			'Pompiere' => 'Pompiere',
			'Prata' => 'Prata',
			'Prociono' => 'Prociono',
			'PT Sans' => 'PT Sans',
			'PT Sans Caption' => 'PT Sans Caption',
			'PT Sans Narrow' => 'PT Sans Narrow',
			'PT Serif' => 'PT Serif',
			'PT Serif Caption' => 'PT Serif Caption',
			'Puritan' => 'Puritan',
			'Quattrocento' => 'Quattrocento',
			'Quattrocento Sans' => 'Quattrocento Sans',
			'Questrial' => 'Questrial',
			'Radley' => 'Radley',
			'Raleway:100' => 'Raleway',
			'Rationale' => 'Rationale',
			'Redressed' => 'Redressed',
			'Rock Salt' => 'Rock Salt',
			'Rochester' => 'Rochester',
			'Rokkitt' => 'Rokkitt',
			'Rosario' => 'Rosario',
			'Ruslan Display' => 'Ruslan Display',
			'Sansita One' => 'Sansita One',
			'Schoolbell' => 'Schoolbell',
			'Shadows Into Light' => 'Shadows Into Light',
			'Shanti' => 'Shanti',
			'Short Stack' => 'Short Stack',
			'Sigmar One' => 'Sigmar One',
			'Six Caps' => 'Six Caps',
			'Slackey' => 'Slackey',
			'Smokum' => 'Smokum',
			'Smythe' => 'Smythe',
			'Sniglet:800' => 'Sniglet',
			'Snippet' => 'Snippet',
			'Sorts Mill Goudy' => 'Sorts Mill Goudy',
			'Special Elite' => 'Special Elite',
			'Spinnaker' => 'Spinnaker',
			'Stardos Stencil' => 'Stardos Stencil',
			'Sue Ellen Francisco' => 'Sue Ellen Francisco',
			'Sunshiney' => 'Sunshiney',
			'Swanky and Moo Moo' => 'Swanky and Moo Moo',
			'Syncopate' => 'Syncopate',
			'Tangerine' => 'Tangerine',
			'Tenor Sans' => ' Tenor Sans',
			'Terminal Dosis Light' => 'Terminal Dosis Light',
			'Tinos' => 'Tinos',
			'Tulpen One' => 'Tulpen One',
			'Ubuntu' => 'Ubuntu',
			'Ultra' => 'Ultra',
			'Unna' => 'Unna',
			'Unkempt' => 'Unkempt',
			'UnifrakturCook:bold' => 'UnifrakturCook',
			'UnifrakturMaguntia' => 'UnifrakturMaguntia',
			'Varela' => 'Varela',
			'Varela Round' => 'Varela Round',
			'Vibur' => 'Vibur',
			'Vidaloka' => 'Vidaloka',
			'Volkhov' => 'Volkhov',
			'Vollkorn' => 'Vollkorn',
			'Voltaire' => 'Voltaire',
			'VT323' => 'VT323',
			'Waiting for the Sunrise' => 'Waiting for the Sunrise',
			'Wallpoet' => 'Wallpoet',
			'Walter Turncoat' => 'Walter Turncoat',
			'Wire One' => 'Wire One',
			'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
			'Yellowtail' => 'Yellowtail',
			'Yeseva One' => 'Yeseva One',
			'Zeyada' => 'Zeyada'),
		"type" => "select"),	

array( "name" => "tab_content_4",
		"type" => "tabcontent-close",
		"icon" => "layout"),
// Close fonts

// Open Social Networking
array( "name" => "tab_content_5",
		"type" => "tabcontent-open",
		"display" => "none",
		"icon" => "layout"),

	array( "name" => "Sociální sítě",
		"type" => "heading",
		"icon" => "layout"),
	
	array( "name" => "Tlačítka pro sdílení obsahu na stránkách",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_share_buttons_page",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select-social"),
	
	array( "name" => "Tlačítka pro sdílení obsahu u příspěvků",
		"desc" => "Tato funkce je dostupná pouze v placené verzi.",
		"id" => $visitpress_shortname."_share_buttons_post",
		"std" => "",
		"class" => "hidden",
		"options" => array(	'a' => 'Display',
							'b' => 'Hide'),
		"type" => "select-social"),


array( "name" => "tab_content_5",
		"type" => "tabcontent-close",
		"icon" => "layout"),
// Close Social Networking


// Open Other settings
array( "name" => "tab_content_6",
		"type" => "tabcontent-open",
		"display" => "none",
		"icon" => "layout"),

	array( "name" => "Další nastavení",
		"type" => "heading",
		"icon" => "layout"),
		

array( "type" => "infotext",
		"name" => "MOŽNOSTI: <a href='widgets.php'>Widgety</a> | <a href='nav-menus.php'>Menu</a> | <a href='themes.php?page=custom-background'>Pozadí</a>"),
    
  array( "name" => "Vlastní CSS",
		"desc" => "Zde můžete vložit vlastní kaskádové styly (CSS).<br />Příklad: #content p {font-size: 15px;} #sidebar p {font-size: 14px;}",
		"id" => $visitpress_shortname."_own_css",
		"type" => "textarea",
		"std" => ""),

array( "name" => "tab_content_6",
		"type" => "tabcontent-close",
		"icon" => "layout"),
// Close Other settings

// Open Get Premium
  array( "name" => "tab_content_7",
		"type" => "tabcontent-open",
		"display" => "none",
		"icon" => "layout"),

	array( "name" => "Získat VisitPress Prémiovou Verzi",
		"type" => "heading",
		"icon" => "layout"),
		
  array( "type" => "infotext",
		"name" => "Jestliže si přejete zakoupit VisitPress Prémiovou Verzi, můžete tak učinit na <a href='http://visitpress.tomastoman.cz/products-page/product-category/visitpress-theme' target='_blank'>Oficiálním webu VisitPressu</a>."),
    
  array( "type" => "infotext",
		"name" => "<strong>Co nabízí VisitPress Prémiová Verze navíc?</strong><br />
    - 5 předdefinovaných barevných schémat<br />
    - Neomezenou možnost vytvářet vlastní barevná schémata<br />
    - Vestavěný widget pro Sociální sítě<br />
    - Vestavěný widget Twitter Following<br />
    - Facebook/Twitter/Google +1 tlačítka pro sdílení na stránkách/příspěvcích<br />
    - Vestavěný widget pro zobrazování lišty Domů/Kontakt/Mapa stránek v záhlaví<br />
    - Automatický generátor Mapy stránek s pokročilými možnostmi nastavení"),
    
  array( "name" => "tab_content_7",
		"type" => "tabcontent-close",
		"icon" => "layout"),
    
// Close Get Premium

array("name" => "Close Container",
		"type" => "container-close",
		"icon" => "layout"),

array( "type" => "close") 
); 


add_action('admin_head', 'visitpress_admin_css');

function visitpress_admin_css() {

		wp_enqueue_style('framework-style', get_template_directory_uri() . '/functions/be/css.css'); ?>
     
	<script language="JavaScript">
		jQuery.noConflict();
		jQuery(document).ready(function($) {
	
		$(".tabs .tab[id^=tab_menu]").click(function() {
			var curMenu=$(this);
			$(".tabs .tab[id^=tab_menu]").removeClass("selected");
			curMenu.addClass("selected");
	
			var index=curMenu.attr("id").split("tab_menu_")[1];
			$(".curvedContainer .tabcontent").css("display","none");
			$(".curvedContainer #tab_content_"+index).css("display","block");
		});
	});
	</script>

<?php }
function visitpress_add_admin() {
	global $visitpress_options; global $visitpress_themename; global $visitpress_shortname;
	if ( isset ( $_GET['page'] ) && ( $_GET['page'] == basename(__FILE__) ) ) {
		if ( isset ($_REQUEST['action']) && ( 'save' == $_REQUEST['action'] ) ){
			foreach ( $visitpress_options as $value ) {
				if ( array_key_exists('id', $value) ) {
					if ( isset( $_REQUEST[ $value['id'] ] ) ) {
						update_option( $value['id'], $_REQUEST[ $value['id'] ]  );
					}
					else {
						delete_option( $value['id'] );
					}
				}
			}
			header("Location: themes.php?page=".basename(__FILE__)."&saved=true");
		}else if ( isset ($_REQUEST['action']) && ( 'reset' == $_REQUEST['action'] ) ) {
			foreach ($visitpress_options as $value) {
				if ( array_key_exists('id', $value) ) {
					delete_option( $value['id'] );
				}
			}
			header("Location: themes.php?page=".basename(__FILE__)."&reset=true");
		}
	}
	add_theme_page($visitpress_themename." nastavení", 'Nastavení šablony', 'edit_theme_options', 'fw-options.php', 'visitpress_admin', '', '1');
}



function visitpress_admin() {
	global $visitpress_themename, $visitpress_shortname, $visitpress_options, $visitpress_themever, $fwver, $visitpress_manualurl; 
	if (isset($_REQUEST["saved"]) && !empty($_REQUEST["saved"])) echo '<div id="message" class="updated fade"><p><strong>'.$visitpress_themename.' nastavení uložena.</strong></p></div>';
	if (isset($_REQUEST["reset"]) && !empty($_REQUEST["reset"])) echo '<div id="message" class="error fade"><p><strong>'.$visitpress_themename.' '.__( 'settings reset.', 'visitpress' ).'</strong></p></div>';
?>

	<div id="wrap_fm"><!-- [ Header ]-->
		<div class="header_fm">
			<div class="logo_fm">Nastavení šablony</div>
			<div class="frame_vers_fm">
				<div class="theme_version_fm"><?php echo $visitpress_themename;?> <strong><?php echo $visitpress_themever;?></strong></div>
				<div class="clear"></div>
			</div>
		</div>

		<!-- [ Top Menu ]-->
		<div class="top_menu_fm">
			<a title="Dokumentace šablony" target="_blank"class="doc_fm" href="<?php echo $visitpress_manualurl; ?>">Dokumentace</a><a title="Zákaznická podpora" target="_blank" class="support_fm" href="http://visitpress.tomastoman.cz/support">Zákaznická podpora</a><a title="VisitPress Prémiová Verze" target="_blank" class="premium_fm" href="http://visitpress.tomastoman.cz/products-page/product-category/visitpress-theme">Získat Prémiovou Verzi</a>
		</div>


	<form method="post">
	<?php 
	foreach ($visitpress_options as $value) {
	switch ( $value['type'] ) {
	case "open":
	?> 
	<?php break; case "title": ?> 

	<!-- [ Body ]-->
	<div id="wrap_body_fm">
	<div class="tabscontainer">


	<?php break; case "close": ?> 

	<!-- start form -->
	<div class="col_100">
		<div class="col_50">
			<input id="submit" class="button-primary" name="save" type="submit" value="Uložit všechny změny" /> <input type="hidden" name="action" value="save" />
			</form>
		</div>
	 	<div class="col_50">
		 	<form method="post">
				<input class="reset" name="reset" type="submit" value="Vrátit výchozí nastavení" />
				<input type="hidden" name="action" value="reset" />
			</form>
		</div>	
		<div class="clear"></div>
    <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FVisitPress%2F717019064981149&amp;width=450&amp;height=80&amp;colorscheme=light&amp;layout=standard&amp;action=like&amp;show_faces=false&amp;send=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px; margin-top: 30px;" allowTransparency="true"></iframe>
	</div>
	<!-- end form -->
</div></div>



<?php break;case 'text': ?>
	<div class="name_fm"><?php echo $value['name']; ?></div>
	<div class="input_fm"><input name="<?php echo $value['id']; ?>" id="<?php echo $value['id']; ?>" type="<?php echo $value['type']; ?>" value="<?php if ( get_option( $value['id'] ) != "") { echo stripslashes(get_option( $value['id'] )); } else { echo $value['std']; } ?>" /></div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>
  
<?php break;case 'color': ?>
	<div class="name_fm"><?php echo isset($value['name']) ? $value['name'] : 0; ?></div>
	<div class="input_fm"><input class="color {hash:true,caps:false,adjust:false,pickerClosable:true}" name="<?php echo $value['id']; ?>" id="<?php echo $value['id']; ?>" type="text" value="<?php if ( get_option( $value['id'] ) != "") { echo stripslashes(get_option( $value['id'] )); } else { echo $value['std']; } ?>" disabled readonly /></div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>

<?php break; case 'textarea':?>
	<div class="name_fm"><?php echo $value['name']; ?></div>
	<div class="input_fm"><textarea name="<?php echo $value['id']; ?>" style="height: 100px;" type="<?php echo $value['type']; ?>" cols="" rows=""><?php if ( get_option( $value['id'] ) != "") { echo stripslashes(get_option( $value['id'] )); } else { echo $value['std']; } ?></textarea></div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>

<?php break; case 'select': ?>
	<div class="name_fm"><?php echo $value['name']; ?></div>
	<div class="input_fm"><select name="<?php echo $value['id']; ?>" id="<?php echo $value['id']; ?>"><?php foreach ($value['options'] as $option) { ?>
	<option <?php if ( get_option( $value['id'] ) == $option) { echo ' selected="selected"'; } elseif ($option == $value['std']) { echo ' selected="selected"'; } ?>><?php echo $option; ?></option>
	<?php } ?>
	</select></div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>
  
  <?php break; case 'select-social': ?>
	<div class="name_fm"><?php echo $value['name']; ?></div>
	<div class="input_fm"><select name="<?php echo $value['id']; ?>" id="<?php echo $value['id']; ?>" disabled><?php foreach ($value['options'] as $option) { ?>
	<option <?php if ( get_option( $value['id'] ) == $option) { echo ' selected="selected"'; } elseif ($option == $value['std']) { echo ' selected="selected"'; } ?>><?php echo $option; ?></option>
	<?php } ?>
	</select></div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>

<?php break; case 'select-category': ?>
	<div class="name_fm"><?php echo $value['name']; ?></div>
	<div class="input_fm">
	
	<select name="<?php echo $value['id']; ?>"><option value="0">- not selected -</option><?php foreach ($value['categoryids'] as $key => $val) { ?><option value="<?php echo"$val";?>"<?php if ( get_option( $value['id'] ) == $val) { echo ' selected="selected"'; } ?>><?php echo $value['categorynames'][$key]; ?></option><?php } ?></select>
	
</select>
	
	</div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>

	<?php break; case "checkbox": ?>
	<div class="name_fm"><?php echo $value['name']; ?></div>
	<div class="input_fm"><?php if(get_option($value['id'])){ $checked = "checked=\"checked\""; }else{ $checked = "";} ?>
	<input type="checkbox" name="<?php echo $value['id']; ?>" id="<?php echo $value['id']; ?>" value="true" <?php echo $checked; ?> /></div>
	<div class="desc_fm"><small><?php echo $value['desc']; ?></small></div>
	
	<?php break; case "heading":?>
	<h1><?php echo $value['name']; ?></h1>
	
	<?php break; case "subheader":?>
	<h2><?php echo $value['name']; ?></h2>
	
<?php break; case "infotext":?>
	<div class="infotext"><?php echo $value['name']; ?></div>
	
		
	<?php break; case "tabs-open":?>	
	<div class="tabs">
	
	<?php break; case "tabs-close":?>	
	</div>	
	
	<?php break; case "tab":?>	
	<div class="tab<?php echo $value['class']; ?>" id="<?php echo $value['id']; ?>">
	<div class="link"><?php echo $value['name']; ?></div>
	<div class="arrow"></div>
	</div>
 	
 	<?php break; case "container-open":?>	
	<div class="curvedContainer">
 	
 	<?php break; case "container-close":?>	
	</div>	
 	
	<?php break; case "tabcontent-open":?>	
	<div class="tabcontent" id="<?php echo $value['name']; ?>" style="display:<?php echo $value['display']; ?>" >
	
	<?php break; case "tabcontent-close":?>	
	</div>
	
 	
<?php break;

}
}
?>

<?php
}

add_action('admin_menu', 'visitpress_add_admin');
?>